<!DOCTYPE html>
<?php 


	// start session
	session_start();
	
	// set time for session timeout
	$currentTime = time() + 25200;
	$expired = 3600;
	
	// if session not set go to login page
	if(!isset($_SESSION['user'])){
		header("location:index.php");
	}
	
	// if current time is more than session timeout back to login page
	if($currentTime > $_SESSION['timeout']){
		session_destroy();
		header("location:index.php");
	}
	
	// destroy previous session timeout and create new one
	unset($_SESSION['timeout']);
	$_SESSION['timeout'] = $currentTime + $expired;
	
?>

<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">



<meta http-equiv="refresh" content="5"/>	
    <meta name="description"
          content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
    <meta name="keywords"
          content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
    <title>رستورانت</title>

    <!-- Favicons-->
    <link rel="icon" href="assets/images/favicon/favicon-32x32.png" sizes="32x32">
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="assets/images/favicon/apple-touch-icon-152x152.png">
    <!-- For iPhone -->
    <meta name="msapplication-TileColor" content="#00bcd4">
    <meta name="msapplication-TileImage" content="assets/images/favicon/mstile-144x144.png">
    <!-- For Windows Phone -->


    <!-- CORE CSS-->
	   <link href="assets/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="assets/css/materialize-rtl.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="assets/css/style.css" type="text/css" rel="stylesheet" media="screen,projection">


    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    <link href="assets/css/prism.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="assets/js/plugins/perfect-scrollbar/perfect-scrollbar.css" type="text/css" rel="stylesheet"
          media="screen,projection">
    <link href="assets/js/plugins/chartist-js/chartist.min.css" type="text/css" rel="stylesheet"
          media="screen,projection">

 
		  
		  
		  <style>
.flip-scale-2-hor-top {
	-webkit-animation: flip-scale-2-hor-top 0.5s linear both;
	        animation: flip-scale-2-hor-top 0.5s linear both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-7-12 18:32:50
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-scale-2-ver-right
 * ----------------------------------------
 */
@-webkit-keyframes flip-scale-2-ver-right {
  0% {
    -webkit-transform: translateX(0) rotateY(0) scale(1);
            transform: translateX(0) rotateY(0) scale(1);
    -webkit-transform-origin: 100% 50%;
            transform-origin: 100% 50%;
  }
  50% {
    -webkit-transform: translateX(50%) rotateY(-90deg) scale(2);
            transform: translateX(50%) rotateY(-90deg) scale(2);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  100% {
    -webkit-transform: translateX(100%) rotateY(-180deg) scale(1);
            transform: translateX(100%) rotateY(-180deg) scale(1);
    -webkit-transform-origin: 0% 50%;
            transform-origin: 0% 50%;
  }
}
@keyframes flip-scale-2-ver-right {
  0% {
    -webkit-transform: translateX(0) rotateY(0) scale(1);
            transform: translateX(0) rotateY(0) scale(1);
    -webkit-transform-origin: 100% 50%;
            transform-origin: 100% 50%;
  }
  50% {
    -webkit-transform: translateX(50%) rotateY(-90deg) scale(2);
            transform: translateX(50%) rotateY(-90deg) scale(2);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  100% {
    -webkit-transform: translateX(100%) rotateY(-180deg) scale(1);
            transform: translateX(100%) rotateY(-180deg) scale(1);
    -webkit-transform-origin: 0% 50%;
            transform-origin: 0% 50%;
  }
}


	#list{
		
		
	    text-align:right;
		
	}
	
	#list-item{
		
	    
		background-color: #ccc;
		padding:4x;
		margin:2px;	
		border-radius:10px;
		
	}
	
	.done{
		
		background-color:green;
	}
	
	.notdone{
		
		background-color:red;
	}

		  
		  </style>
</head>

<body>
<!-- START HEADER -->
<header id="header" class="page-topbar" style="font-family:B Nazanin;font-size:24px;">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <nav class="cyan">
            <div class="nav-wrapper">
                <h1 class="logo-wrapper"><a href="dashboard.php" class="brand-logo darken-1 center"><img
                        src="assets/images/materialize-logo.png" alt="materialize logo"></a> <span
                        class="logo-text">برنامه رستورانت شما</span></h1>
            <!--    <ul class="right hide-on-med-and-down">
                    <li><a href="#push-notification" target="_blank"
                           class="waves-effect waves-block waves-light modal-trigger"><i
                            class="mdi-social-notifications"></i></a>
                    </li>
                    <!-- Dropdown Trigger
                    <li><a class="dropdown-button" href="javascript:void(0);"
                           data-activates="dropdown1"><i class="mdi-navigation-arrow-drop-down"></i></a>
                    </li>

                    <!-- Dropdown Structure 
                    <ul id="dropdown1" class="dropdown-content">
                       <!-- <li><a href="admin.php">Settings</a></li>
                        <li><a href="logout.php">Logout</a></li> 
						<li><a href="admin.php">تنظیمات</a></li>
                        <li><a href="logout.php">خروج</a></li>
                    </ul>

                </ul> -->
            </div>
        </nav>
    </div>
    <!-- end header nav-->
</header>
        <!--breadcrumbs start-->
        <div id="breadcrumbs-wrapper" class=" grey lighten-3">
          	<div class="container">
			
            	<div class="row">
              		<div class="col s12 m12 l12">
                      <h6 class="breadcrumbs-title">قلیان</h6>   			
		
              		</div>
            	</div>
          	</div>
        </div>

<?php
	
	//header('Content-Type:text/html;charset=UTF-8');
	$host = "localhost";
	$db   = "restaurant";
	$user = "root";
	$pass = "";
	
	$conn = mysqli_connect($host,$user,$pass,$db);
	$conn->set_charset("utf8");
	$s = mysqli_query($conn,"select * from order_list_view where res_status = 0 AND category_id =2 group by order_id order by order_id DESC");
	
	
	
 ?>
 
	<table class="bordered">
	<tr>
	<thead>
	
		<th style="text-align:center;background-color:#fdb94e; color:white;">اسم گارسون</th>
		<th style="text-align:center;background-color:white; color:#000;;">تاریخ و ساعت</th>
		<th style="text-align:center;background-color:#008bcf; color:white;">نمبر میز</th>
		<th style="text-align:center;background-color:#ccc; color:white;">سفارشات</th>
		
	</thead>
	</tr>
	<tbody>
  
    <?php while($data = mysqli_fetch_array($s)){ ?>
			     <?php $a= $data[2];
				
				$db_time = substr($data[2],11,strpos($data[2],' '));
				
				$time = date('h:i A',strtotime($db_time));
			 ?>
		<tr style="padding:0;">
			
			<td style="width:200px; background-color:#fdb94e; text-align:center;">  <?php echo $data[6] ?> </td>
			<td style="width:200px; background-color:white; text-align:center;font-size:36px;">  <?php echo $time ?> </td>
			<td style="width:100px; background-color:dodgerblue; text-align:center; font-size:36px;  color:white;">  <?php echo $data[5] ?> </td>
			
			<td style ="padding:0 20px 0 20px;"> <ul id="list">
			<?php 	 
			
			$menu_list = mysqli_query($conn,"select * from order_list_view where order_id = '$data[0]' AND category_id =2");
			while($item = mysqli_fetch_array($menu_list)){ ?>
					
			       
				   <?php if($item[14] == 1){?>
				   <li id="list-item" style="background-color:#0af167; color:green;">  <span style="width:60px; background-color:#e9e8dd; border-radius:0 10px 10px 0; padding:30; display:inline-block; text-align:center; font-size:1.5em;"> <?php  echo $item[13]; ?> </span>    <?php echo $item[9]; ?>  </li>
				   <?php }else { ?>
				   <li id="list-item" style="background-color:#ffaaaa;"> <span style="width:60px; background-color:#e9e8dd; border-radius:0 10px 10px 0; padding:3; display:inline-block; text-align:center; font-size:1.5em;"> <?php  echo $item[13]; ?> </span> <?php echo $item[9]; ?> </li>
				   <?php } ?>
					
		<?php 	} ?>
		</ul>
		</td>
		</tr>
<?php	}?> 
	
		 
	</tbody>
	</table>
</body>
</html>