<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="description"
          content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
    <meta name="keywords"
          content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
	
	
		  
    <title>رستورانت</title>

    <!-- Favicons-->
    <link rel="icon" href="assets/images/favicon/favicon-32x32.png" sizes="32x32">
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="assets/images/favicon/apple-touch-icon-152x152.png">
    <!-- For iPhone -->
    <meta name="msapplication-TileColor" content="#00bcd4">
    <meta name="msapplication-TileImage" content="assets/images/favicon/mstile-144x144.png">
    <!-- For Windows Phone -->


    <!-- CORE CSS-->

    <link href="assets/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection">
	
    <link href="assets/css/materialize-rtl.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="assets/css/style.css" type="text/css" rel="stylesheet" media="screen,projection">


    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    <link href="assets/css/prism.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="assets/js/plugins/perfect-scrollbar/perfect-scrollbar.css" type="text/css" rel="stylesheet"
          media="screen,projection">
    <link href="assets/js/plugins/chartist-js/chartist.min.css" type="text/css" rel="stylesheet"
          media="screen,projection">
		  
		  
		  <style>
.flip-scale-2-hor-top {
	-webkit-animation: flip-scale-2-hor-top 0.5s linear both;
	        animation: flip-scale-2-hor-top 0.5s linear both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-7-12 18:32:50
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-scale-2-ver-right
 * ----------------------------------------
 */
@-webkit-keyframes flip-scale-2-ver-right {
  0% {
    -webkit-transform: translateX(0) rotateY(0) scale(1);
            transform: translateX(0) rotateY(0) scale(1);
    -webkit-transform-origin: 100% 50%;
            transform-origin: 100% 50%;
  }
  50% {
    -webkit-transform: translateX(50%) rotateY(-90deg) scale(2);
            transform: translateX(50%) rotateY(-90deg) scale(2);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  100% {
    -webkit-transform: translateX(100%) rotateY(-180deg) scale(1);
            transform: translateX(100%) rotateY(-180deg) scale(1);
    -webkit-transform-origin: 0% 50%;
            transform-origin: 0% 50%;
  }
}
@keyframes flip-scale-2-ver-right {
  0% {
    -webkit-transform: translateX(0) rotateY(0) scale(1);
            transform: translateX(0) rotateY(0) scale(1);
    -webkit-transform-origin: 100% 50%;
            transform-origin: 100% 50%;
  }
  50% {
    -webkit-transform: translateX(50%) rotateY(-90deg) scale(2);
            transform: translateX(50%) rotateY(-90deg) scale(2);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  100% {
    -webkit-transform: translateX(100%) rotateY(-180deg) scale(1);
            transform: translateX(100%) rotateY(-180deg) scale(1);
    -webkit-transform-origin: 0% 50%;
            transform-origin: 0% 50%;
  }
}

@media print
{
header
{
	
	display:none;
}	
}

		  
		  </style>
</head>

<body>

<?php $username = $_SESSION['user'];

	$host = "localhost";
	$db   = "restaurant";
	$user = "root";
	$pass = "";
	
	$user_role;
	
	$conn = mysqli_connect($host,$user,$pass,$db);
	$conn->set_charset("utf8");
	
	$query = mysqli_query($conn,"select * from tbl_user where username='$username'");
	
	while($role = mysqli_fetch_array($query)) {
		
		$user_role = $role['role'];
	}
	
 ?>



<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START HEADER -->
<header id="header" class="page-topbar" style="font-family:B Nazanin;font-size:24px;">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <nav class="cyan">
            <div class="nav-wrapper" style="background-color:#c97d03;">
                <h1 class="logo-wrapper"><a href="dashboard.php" class="brand-logo darken-1 center">Karim Continental Restaurant</a> <span
                        class="logo-text">برنامه رستورانت شما</span></h1>
                <ul class="right hide-on-med-and-down">
                 <!--   <li><a href="#push-notification" target="_blank"
                           class="waves-effect waves-block waves-light modal-trigger"><i
                            class="mdi-social-notifications"></i></a>
                    </li>-->
                    <!-- Dropdown Trigger -->
                    <li><a class="dropdown-button" href="javascript:void(0);"
                           data-activates="dropdown1"><i class="mdi-navigation-arrow-drop-down"></i></a>
                    </li>

                    <!-- Dropdown Structure -->
                    <ul id="dropdown1" class="dropdown-content">
                       <!-- <li><a href="admin.php">Settings</a></li>
                        <li><a href="logout.php">Logout</a></li> -->
						<li><a href="admin.php">تنظیمات</a></li>
                        <li><a href="logout.php">خروج</a></li>
                    </ul>

                </ul>
            </div>
        </nav>
    </div>
    <!-- end header nav-->
</header>
<!-- END HEADER -->

<!-- START MAIN -->
<div id="main">
    <!-- START WRAPPER -->
    <div class="wrapper" style="font-family:B Nazanin;font-size:20px;">

        <!-- START LEFT SIDEBAR NAV-->
        <aside id="right-sidebar-nav">
            <ul id="slide-out" class="side-nav fixed leftside-navigation">
                <li class=" cyan darken-2" >
                    <div class="row" style="background-color:#F19A0F;">
                        <div class="col col s4 m4 l4">
                            <center>
                                <img src="assets/images/ic_launcher.png" width="100px" height="100px">
                            </center>
                        </div>
                    </div>
                </li>
				
				<?php if($user_role==1) { ?> 
                <li class="bold">
                    <a href="dashboard.php" class="waves-effect waves-cyan" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-action-dashboard" ></i>صفحه اصلی
                    </a>
                </li
				<?php }	?>
			<!-- kitchen acces right mapping -->
			
				<?php if($user_role==1 || $user_role==3) { ?>
                <li class="bold">
                    <a href="manage_kitchen.php" class="waves-effect waves-cyan"style="font-family:B Nazanin;font-size:24px;" >
                        <i class="mdi-action-shopping-cart"></i>مدیریت آشپزخانه
                    </a>
                </li>
				
				
				  <li class="bold">
                    <a href="kitchen.php" class="waves-effect waves-cyan" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-action-store"></i>آشپزخانه
                    </a>
                </li>
				<?php } ?>
				
				<!-- qail acces right mapping -->
				<?php if($user_role==1 || $user_role==4) { ?>
				 <li class="bold">
                    <a href="manage_qail.php" class="waves-effect waves-cyan"style="font-family:B Nazanin;font-size:24px;" >
                        <i class="mdi-action-shopping-cart"></i>مدیریت قلیان
                    </a>
                </li>
				
				
				  <li class="bold">
                    <a href="qail.php" class="waves-effect waves-cyan" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-action-store"></i>قلیان
                    </a>
                </li>
				<?php } ?>

				<!-- qail acces right mapping -->
				<?php if($user_role==1 || $user_role==5) { ?>				
				 <li class="bold">
                    <a href="manage_juice.php" class="waves-effect waves-cyan"style="font-family:B Nazanin;font-size:24px;" >
                        <i class="mdi-action-shopping-cart"></i>مدیریت نوشیدنی ها
                    </a>
                </li>
				
				
				  <li class="bold">
                    <a href="juice.php" class="waves-effect waves-cyan" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-action-store"></i>نوشیدنی ها
                    </a>
                </li>
				<?php } ?>				
				

				<!-- qail acces right mapping -->
				<?php if($user_role==1 || $user_role==2) { ?>				
				  <li class="bold">
                    <a href="management.php" class="waves-effect waves-cyan" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-editor-attach-money"></i>مدیریت مالی
                    </a>
                </li>
				<?php } ?>
				
				<!-- qail acces right mapping -->
				<?php if($user_role==1) { ?>				
				<li class="bold">
                    <a href="general-management.php" class="waves-effect waves-user" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-action-shopping-cart"></i>مدیریت عمومی
                    </a>
                </li>

				
                <li class="bold">
                    <a href="category.php" class="waves-effect waves-cyan" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-action-list"></i>کتگوری
                    </a>
                </li>                

                <li class="bold">
                    <a href="menu.php" class="waves-effect waves-cyan" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-action-store"></i>منوی رستورانت
                    </a>
                </li>
<!--
                <li class="bold">
                    <a href="gallery.php" class="waves-effect waves-cyan">
                        <i class="mdi-image-collections"></i>Gallery
                    </a>
                </li>  

                 <li class="bold">
                    <a href="news.php" class="waves-effect waves-cyan">
                        <i class="mdi-action-description"></i>News
                    </a>
                </li>           
-->			
<!--	

                <li class="bold">
                    <a href="setting.php" class="waves-effect waves-cyan" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-editor-attach-money"></i>تنظیمات واحد پولی
                    </a>
                </li>
				
				
				-->
				
				<li class="bold">
                    <a href="garson.php" class="waves-effect waves-cyan" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-editor-attach-list"></i>اضافه کردن گارسون
                    </a>
                </li>
				
				<li class="bold">
                    <a href="report/paidReport.php" class="waves-effect waves-cyan" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-editor-attach-list"></i>راپور فروشات
                    </a>
                </li>				<li class="bold">
                    <a href="report/cancelReport.php" class="waves-effect waves-cyan" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-editor-attach-list"></i>راپور کنسل

                    </a>
                </li>				<li class="bold">
                    <a href="report/menu-report.php" class="waves-effect waves-cyan" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-editor-attach-list"></i>راپور منوی
                    </a>
                </li>			
				
				
				
				

                <li class="bold">
                    <a href="admin.php" class="waves-effect waves-cyan" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-action-settings"></i>تنظیمات
                    </a>
                </li>     
				
				<?php } ?>
				
                <li class="bold">
                    <a href="logout.php" class="waves-effect waves-cyan" style="font-family:B Nazanin;font-size:24px;">
                        <i class="mdi-action-settings-power"></i>خروج
                    </a>
                </li>

            </ul>
            <a href="#" data-activates="slide-out"
               class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only darken-2"><i
                    class="mdi-navigation-menu"></i></a>
        </aside>
        <!-- END LEFT SIDEBAR NAV-->

        <!-- ////////////////////////////////////////////////////////////////////////////

        <div id="push-notification" class="modal">

            <div class="modal-content">
                <h4>معلومات</h4>
                <hr>
                <p>we provide two options for push notifications service from Firebase and Onesignal, you can use one or both at once.</p>
                <p>you will be directed to web site which related with push notification services</p>
            </div>

            <div class="modal-footer">
                <a href="https://console.firebase.google.com" target="_blank" class="waves-effect waves-red btn-flat modal-action modal-close">فایربیس</a>
                <a href="https://onesignal.com/" target="_blank" class="waves-effect waves-green btn-flat modal-action modal-close">OneSignal</a>
            </div>
            
        </div> -->
		
		sc
		
		
		
		
		