<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">



<!--<meta http-equiv="refresh" content="5"/>-->	
    <meta name="description"
          content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
    <meta name="keywords"
          content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
    <title>رستورانت</title>

    <!-- Favicons-->
    <link rel="icon" href="assets/images/favicon/favicon-32x32.png" sizes="32x32">
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="assets/images/favicon/apple-touch-icon-152x152.png">
    <!-- For iPhone -->
    <meta name="msapplication-TileColor" content="#00bcd4">
    <meta name="msapplication-TileImage" content="assets/images/favicon/mstile-144x144.png">
    <!-- For Windows Phone -->


    <!-- CORE CSS-->

    <link href="assets/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="assets/css/materialize-rtl.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="assets/css/style.css" type="text/css" rel="stylesheet" media="screen,projection">


    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    <link href="assets/css/prism.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="assets/js/plugins/perfect-scrollbar/perfect-scrollbar.css" type="text/css" rel="stylesheet"
          media="screen,projection">
    <link href="assets/js/plugins/chartist-js/chartist.min.css" type="text/css" rel="stylesheet"
          media="screen,projection">
		  
		  
		  <style>
.flip-scale-2-hor-top {
	-webkit-animation: flip-scale-2-hor-top 0.5s linear both;
	        animation: flip-scale-2-hor-top 0.5s linear both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-7-12 18:32:50
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-scale-2-ver-right
 * ----------------------------------------
 */
@-webkit-keyframes flip-scale-2-ver-right {
  0% {
    -webkit-transform: translateX(0) rotateY(0) scale(1);
            transform: translateX(0) rotateY(0) scale(1);
    -webkit-transform-origin: 100% 50%;
            transform-origin: 100% 50%;
  }
  50% {
    -webkit-transform: translateX(50%) rotateY(-90deg) scale(2);
            transform: translateX(50%) rotateY(-90deg) scale(2);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  100% {
    -webkit-transform: translateX(100%) rotateY(-180deg) scale(1);
            transform: translateX(100%) rotateY(-180deg) scale(1);
    -webkit-transform-origin: 0% 50%;
            transform-origin: 0% 50%;
  }
}
@keyframes flip-scale-2-ver-right {
  0% {
    -webkit-transform: translateX(0) rotateY(0) scale(1);
            transform: translateX(0) rotateY(0) scale(1);
    -webkit-transform-origin: 100% 50%;
            transform-origin: 100% 50%;
  }
  50% {
    -webkit-transform: translateX(50%) rotateY(-90deg) scale(2);
            transform: translateX(50%) rotateY(-90deg) scale(2);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  100% {
    -webkit-transform: translateX(100%) rotateY(-180deg) scale(1);
            transform: translateX(100%) rotateY(-180deg) scale(1);
    -webkit-transform-origin: 0% 50%;
            transform-origin: 0% 50%;
  }
}


		  
		  </style>
</head>

<body>

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START HEADER -->
<header id="header" class="page-topbar" style="font-family:B Nazanin;font-size:24px;">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <nav class="cyan">
            <div class="nav-wrapper">
                <h1 class="logo-wrapper"><a href="dashboard.php" class="brand-logo darken-1 center"><img
                        src="assets/images/materialize-logo.png" alt="materialize logo"></a> <span
                        class="logo-text">برنامه رستورانت شما</span></h1>
                <ul class="right hide-on-med-and-down">
                    <li><a href="#push-notification" target="_blank"
                           class="waves-effect waves-block waves-light modal-trigger"><i
                            class="mdi-social-notifications"></i></a>
                    </li>
                    <!-- Dropdown Trigger -->
                    <li><a class="dropdown-button" href="javascript:void(0);"
                           data-activates="dropdown1"><i class="mdi-navigation-arrow-drop-down"></i></a>
                    </li>

                    <!-- Dropdown Structure -->
                    <ul id="dropdown1" class="dropdown-content">
                       <!-- <li><a href="admin.php">Settings</a></li>
                        <li><a href="logout.php">Logout</a></li> -->
						<li><a href="admin.php">تنظیمات</a></li>
                        <li><a href="logout.php">خروج</a></li>
                    </ul>

                </ul>
            </div>
        </nav>
    </div>
    <!-- end header nav-->
</header>
<!-- END HEADER -->



<?php
	//include_once('includes/connect_database.php'); 
//	include_once('functions.php'); 
	
	?>
	


<!-- END HEADER -->


<?php

$con=mysqli_connect("localhost","root","","restaurant");
// Check connection
if (mysqli_connect_errno())
{
echo "Failed to connect to MySQL: " . mysqli_connect_error();
}

//$result = mysqli_query($con,"SELECT * FROM order_list_view");
$result = mysqli_query($con,"SELECT order_id, number_of_people, qty, status FROM order_list_view");












echo "<table border='1'>
<tr>
<th>Order ID</th>
<th>Table NO</th>
<th>qty</th>
<th>status</th>
</tr>";

while($row = mysqli_fetch_array($result))
{
	
echo "<tr>";
echo "<td>" . $row['order_id'] . "</td>";
echo "<td>" . $row['number_of_people'] . "</td>";
echo "<td>" . $row['qty'] . "</td>";
if($row['status'] == 0)
{
	echo "<td style='color:red;'>" . $row['status'] . "</td>";
}else{
echo "<td>" . $row['status'] . "</td>";
}
echo "</tr>";
	
}
echo "</table>";



// other part



$orders = mysqli_query($con,"SELECT name,order_id 
FROM order_list
");




		echo "<table border='1'>
		<tr>
		<th>Order ID</th>
		<th>Table NO</th>

		</tr>";

		while($row = mysqli_fetch_array($orders))
		{
			
		echo "<tr>";
		
		if($row['order_id'] === $row['order_id']){
		echo "<td style='background:red'>" . $row['order_id'] . "</td>";
		echo "<td>" . $row['name'] . "</td>";
		}else{
		echo "not equal";
	
		}
		echo "</tr>";
			
		}
		echo "</table>";




////"SELECT * FROM prouct inner JOIN brand ON prouct.br_id = brand.br_id";


echo "other part:"."<br>" ;
echo "other part:"."<br>" ;
echo "other part:"."<br>" ;

//ELECT Orders.OrderID, Customers.CustomerName
//FROM (Orders
//INNER JOIN Customers ON Orders.CustomerID = Customers.CustomerID);




$inner = mysqli_query($con,"SELECT order_list.name,order_list,qty,order_list.status,order_list_view.order_id
FROM(order_list
INNER JOIN order_list_view ON order_list.order_id = order_list_view.order_id)
");






		echo "<table border='1'>
		<tr>
		<th>Order ID</th>
		<th>Table NO</th>
		</tr>";

		while($row = mysqli_fetch_array($inner))
		{
			
		echo "<tr>";
		
		echo "<td>" . $row['name'] . "</td>";
	
	
		}
		echo "</tr>";
			
		
		echo "</table>";






mysqli_close($con);
?>

	
	



</body>

	
					
				