<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">



<meta http-equiv="refresh" content="5"/>	
    <meta name="description"
          content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
    <meta name="keywords"
          content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
    <title>رستورانت</title>

    <!-- Favicons-->
    <link rel="icon" href="assets/images/favicon/favicon-32x32.png" sizes="32x32">
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="assets/images/favicon/apple-touch-icon-152x152.png">
    <!-- For iPhone -->
    <meta name="msapplication-TileColor" content="#00bcd4">
    <meta name="msapplication-TileImage" content="assets/images/favicon/mstile-144x144.png">
    <!-- For Windows Phone -->


    <!-- CORE CSS-->

    <link href="assets/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="assets/css/materialize-rtl.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="assets/css/style.css" type="text/css" rel="stylesheet" media="screen,projection">


    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    <link href="assets/css/prism.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="assets/js/plugins/perfect-scrollbar/perfect-scrollbar.css" type="text/css" rel="stylesheet"
          media="screen,projection">
    <link href="assets/js/plugins/chartist-js/chartist.min.css" type="text/css" rel="stylesheet"
          media="screen,projection">
		  
		  
		  <style>
.flip-scale-2-hor-top {
	-webkit-animation: flip-scale-2-hor-top 0.5s linear both;
	        animation: flip-scale-2-hor-top 0.5s linear both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-7-12 18:32:50
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-scale-2-ver-right
 * ----------------------------------------
 */
@-webkit-keyframes flip-scale-2-ver-right {
  0% {
    -webkit-transform: translateX(0) rotateY(0) scale(1);
            transform: translateX(0) rotateY(0) scale(1);
    -webkit-transform-origin: 100% 50%;
            transform-origin: 100% 50%;
  }
  50% {
    -webkit-transform: translateX(50%) rotateY(-90deg) scale(2);
            transform: translateX(50%) rotateY(-90deg) scale(2);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  100% {
    -webkit-transform: translateX(100%) rotateY(-180deg) scale(1);
            transform: translateX(100%) rotateY(-180deg) scale(1);
    -webkit-transform-origin: 0% 50%;
            transform-origin: 0% 50%;
  }
}
@keyframes flip-scale-2-ver-right {
  0% {
    -webkit-transform: translateX(0) rotateY(0) scale(1);
            transform: translateX(0) rotateY(0) scale(1);
    -webkit-transform-origin: 100% 50%;
            transform-origin: 100% 50%;
  }
  50% {
    -webkit-transform: translateX(50%) rotateY(-90deg) scale(2);
            transform: translateX(50%) rotateY(-90deg) scale(2);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  100% {
    -webkit-transform: translateX(100%) rotateY(-180deg) scale(1);
            transform: translateX(100%) rotateY(-180deg) scale(1);
    -webkit-transform-origin: 0% 50%;
            transform-origin: 0% 50%;
  }
}


		  
		  </style>
</head>

<body>

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START HEADER -->
<header id="header" class="page-topbar" style="font-family:B Nazanin;font-size:24px;">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <nav class="cyan">
            <div class="nav-wrapper">
                <h1 class="logo-wrapper"><a href="dashboard.php" class="brand-logo darken-1 center"><img
                        src="assets/images/materialize-logo.png" alt="materialize logo"></a> <span
                        class="logo-text">برنامه رستورانت شما</span></h1>
                <ul class="right hide-on-med-and-down">
                    <li><a href="#push-notification" target="_blank"
                           class="waves-effect waves-block waves-light modal-trigger"><i
                            class="mdi-social-notifications"></i></a>
                    </li>
                    <!-- Dropdown Trigger -->
                    <li><a class="dropdown-button" href="javascript:void(0);"
                           data-activates="dropdown1"><i class="mdi-navigation-arrow-drop-down"></i></a>
                    </li>

                    <!-- Dropdown Structure -->
                    <ul id="dropdown1" class="dropdown-content">
                       <!-- <li><a href="admin.php">Settings</a></li>
                        <li><a href="logout.php">Logout</a></li> -->
						<li><a href="admin.php">تنظیمات</a></li>
                        <li><a href="logout.php">خروج</a></li>
                    </ul>

                </ul>
            </div>
        </nav>
    </div>
    <!-- end header nav-->
</header>
<!-- END HEADER -->
<!-- START HEADER -->
<header id="header" class="page-topbar" style="font-family:B Nazanin;font-size:24px;">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <nav class="cyan">
            <div class="nav-wrapper">
                <h1 class="logo-wrapper"><a href="dashboard.php" class="brand-logo darken-1 center"><img
                        src="assets/images/materialize-logo.png" alt="materialize logo"></a> <span
                        class="logo-text">برنامه رستورانت شما</span></h1>
                <ul class="right hide-on-med-and-down">
                    <li><a href="#push-notification" target="_blank"
                           class="waves-effect waves-block waves-light modal-trigger"><i
                            class="mdi-social-notifications"></i></a>
                    </li>
                    <!-- Dropdown Trigger -->
                    <li><a class="dropdown-button" href="javascript:void(0);"
                           data-activates="dropdown1"><i class="mdi-navigation-arrow-drop-down"></i></a>
                    </li>

                    <!-- Dropdown Structure -->
                    <ul id="dropdown1" class="dropdown-content">
                       <!-- <li><a href="admin.php">Settings</a></li>
                        <li><a href="logout.php">Logout</a></li> -->
						<li><a href="admin.php">تنظیمات</a></li>
                        <li><a href="logout.php">خروج</a></li>
                    </ul>

                </ul>
            </div>
        </nav>
    </div>
    <!-- end header nav-->
</header>
<!-- END HEADER -->



<?php
	include_once('includes/connect_database.php'); 
	include_once('functions.php'); 
	
?>

	<?php 
		// create object of functions class
		$function = new functions;
		
		$orderlist_changer;
		
		
		// create array variable to store data from database
		$data = array();
		
		if(isset($_GET['keyword'])){	
			// check value of keyword variable
			$keyword = $function->sanitize($_GET['keyword']);
			$bind_keyword = "%".$keyword."%";
		}else{
			$keyword = "";
			$bind_keyword = $keyword;
		}
		
		// get all data from pemesanan table
		if(empty($keyword)){
			$sql_query = "SELECT ID, name, number_of_people, date_time, phone, status, order_list
				FROM tbl_reservation  
				ORDER BY ID DESC";
		}else{
			$sql_query = "SELECT ID, name, number_of_people, date_time, phone, status, order_list
				FROM tbl_reservation 
				WHERE name LIKE ? 
				ORDER BY ID DESC";
		}
		
		
		$qry = "select * from order_list_view";
		
		
			
		$stmt = $connect->stmt_init();
		if($stmt->prepare($qry)) {	
			// Bind your variables to replace the ?s
			if(!empty($keyword)){
				$stmt->bind_param('ssss', $bind_keyword);
			}
			// Execute query
			$stmt->execute();
			// store result 
			$stmt->store_result();
			$stmt->bind_result($data['waiter_name'], 
					$data['phone'],	/* phone = table_number */				
					$data['date_time'], 
					$data['menu_name']
					);
					
					$orderlist_changer =$data['menu_name'];
					
					
					
			// get total records
			$total_records = $stmt->num_rows;
		}
		
		
		// check page parameter
		if(isset($_GET['page'])){
			$page = $_GET['page'];
		}else{
			$page = 1;
		}
		
		// number of data that will be display per page
		$offset = 20;
							
		//lets calculate the LIMIT for SQL, and save it $from
		if ($page){
			$from 	= ($page * $offset) - $offset;
		}else{
			//if nothing was given in page request, lets load the first page
			$from = 0;	
		}
		
		// get all data from pemesanan table SUCCESS CHANGE
		if(empty($keyword)){
			$sql_query = "SELECT ID, name, number_of_people, date_time, phone, status, order_list,order_list
				FROM tbl_reservation WHERE status='0'
				ORDER BY ID DESC 
				LIMIT ?, ?";
		}else{
			$sql_query = "SELECT ID, name, number_of_people, date_time, phone, status, order_list, order_list
				FROM tbl_reservation 
				WHERE name LIKE ? 
				ORDER BY ID ASC 
				LIMIT ?, ?";
		}
		
		
		
		
		
		$stmt_paging = $connect->stmt_init();
		if($stmt_paging ->prepare($qry)) {
			// Bind your variables to replace the ?s
			if(empty($keyword)){
				$stmt_paging ->bind_param('ss', $from, $offset);
			}else{
				$stmt_paging ->bind_param('sss', $bind_keyword, $from, $offset);
			}
			// Execute query
			$stmt_paging ->execute();
			// store result 
			$stmt_paging ->store_result();
			
			$stmt_paging ->bind_result($data['waiter_name'], 
					$data['phone'],	/* phone = table_number */				
					$data['date_time'], 
					$data['order_list']
					);
					
					
			
			// for paging purpose
			$total_records_paging = $total_records; 
		}
		
					
					
						
		// if no data on database show "Tidak Ada Pemesanan"
		if($total_records_paging == 0){
	?>


	
	<!-- START CONTENT -->
    <section id="content">

        <!--breadcrumbs start-->
        <div id="breadcrumbs-wrapper" class=" grey lighten-3">
          	<div class="container">
            	<div class="row">
              		<div class="col s12 m12 l12">
               			<h5 class="breadcrumbs-title">لیست ریزرف</h5>
		                <ol class="breadcrumb">
		                  <li><a href="dashboard.php">صفحه اصلی</a>
		                  </li>
		                  <li><a href="#" class="active">لیست ریزرف</a>
		                  </li>
		                </ol>
              		</div>
            	</div>
          	</div>
        </div>
        <!--breadcrumbs end-->

        <!--start container-->
        <div class="container">
          	<div class="section">         		      

			


			÷	<div class="col s12 m12 l9">
				    <div class="row">
				        <form method="get" class="col s12">
				            <div class="row">
								<div class="input-field col s12">
				                    <h5>هیچ ریزرفی یافت نشد</h5>
				                </div>
				             </div>
				        </form>
				    </div>
				</div>
			</div>
		</div>
	</section>
	<br><br><br><br><br><br><br><br><br><br>
	
	<?php
		// otherwise, show data
		}else{ $row_number = $from + 1;?>
	

	<!-- START CONTENT -->

            
				<div class="row">
		            <div class="col-md-12 s12 m12 l12">
		              	<div class="card-panel">
		                	<div class="row">
		                  		<div class="row">
		                    		<div class="input-field col s12">
	
										<table class='table bordered hoverable condensed' style="width:100%">
										<thead>
										<!--	<tr>
												<th><div align="right">Name</div></th>
												<th><div align="right">Number of People</div></th>
												<th><div align="right">Phone</div></th>
												<th><div align="right">Email</div></th>
												<th><div align="right">Date & Time</div></th>
												<th><div align="right">Status</div></th>
												<th><div align="right">Action</div></th>
											</tr>
											-->
											<tr style="background:rgb(149,74,74);color:white; border:1px solid black;font-family:B Nazanin;font-size:24px;">
												
												
												
												<th style="border:1px solid white;border-radius:2px;"><div align="center">اسم گارسون</div></th>
												<th style="border:1px solid white;width:100px;border-radius:2px;"><div align="center">شماره میز</div></th>
												<th style="border:1px solid white;width:100px;border-radius:2px;"><div align="center">تاریخ و ساعت</div></th>
												<th style="border:1px solid white;border-radius:2px;"><div align="center">سفارشات</div></th>
											</tr>
											
										</thead>
											
											<?php 
												while ($stmt_paging->fetch()){ ?>
												<tbody>
													<tr  style="font-family:B Nazanin;font-size:20px;" >
														
														
														<td class="flip-scale-2-hor-top" style="border:1px solid black;position:relative;width:100px;"><div align="center"><?php echo $data['name'];?></div></td>
														<td class="flip-scale-2-hor-top" style="border:1px solid black;background:rgb(255,126,64);font-size:40px;"><div align="center"><?php echo $data['number_of_people'];?> </div></td>
														<td class="flip-scale-2-hor-top" style="border:1px solid black;"><div align="center"><b><?php echo $data['date_time'];?></div></b></td>
														
														<?php
														//	$order = $data['order_list'];
															// $order= substr($order,0,strpos($order,'Total :'));
															 
															 
															// $number_of_sign = substr_count($order,"?");
															 //$size=0;
															 //$orders =null;
															 //for($i=0;$i < $number_of_sign;$i++)
														//	 {
															//	 $order1= substr($order,$size,strpos($order,'?'));
															//	$orders=$orders.$order1."<br>"."<br>";
															 
															//	  $size += strlen($order1)+1;
																//  echo "<br> this is the size:".$size;
																  
																  //echo $order1;
																 // $order= substr($order,$size+1,strpos($order,'?'));
															// }
															 
															
															 
														?>
														<td class="flip-scale-2-hor-top" style="border:1px solid black;background:"><div align="center"><b><?php echo $data['order_list'];?></b></div></td>

														
														
														
														<!--<td><div align="right"><?php //echo $data['order_list'];?></div></td>-->
																																								
														
													</tr>
												</tbody>
													<?php 
													} 
												}
											?>
										</table>
										
	
												


										<h4><?php $function->doPages($offset, 'kitchen.php', '', $total_records, $keyword); ?></h4>

		                    		</div>
		                  		</div>
		                	</div>
		              	</div>
		            </div>
		        </div>
        	</div>
        </div>

	</section>	

<script >


</script>
<?php 
	$stmt->close();
	include_once('includes/close_database.php'); ?>
					
				